### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mojtabakaviani** [madskristensen/CssTools#10]
at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 109&#x000D;&#x000A;   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.&lt;&gt;c__DisplayClass4_0.&lt;GetClassifier&gt;b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

and

at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45&#x000D;&#x000A;   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116&#x000D;&#x000A;   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.&lt;&gt;c__DisplayClass4_0.&lt;GetClassifier&gt;b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Visual Studio 2017 15.8 Preview 2

**Comment by vaindil** [comment]
Same here on 15.8 Preview 3.

**Comment by AccessIT** [comment]
I have had it on opening a **.aspx** file in source mode on 15.8 preview 3 and now preview 4

System.NullReferenceException: Object reference not set to an instance of an object.   at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59   at CssTools.VendorClassifierProvider.<>c__DisplayClass4_0.<GetClassifier>b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.<>c__DisplayClass12_0`1.<CreateTagger>b__0(IClassifierProvider provider)   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource
--

**Comment by tushroy** [comment]
**Following exception occurred opening project in Visual Studio community 2017 version 15.8.0**

System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45&#x000D;&#x000A;   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116&#x000D;&#x000A;   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.&lt;&gt;c__DisplayClass4_0.&lt;GetClassifier&gt;b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)

**Comment by Kozhuharov** [comment]
> Following exception occurred opening project in Visual Studio community 2017 version 15.8.0

@tushroy After re-install the plugin and restart visual studio everything seems fine. No more this error on VS Pro 2017 v15.8.0
