### ISSUE TITLE
Possible bug - Reproducable - Crashes Visual Studio 2017

### ISSUE THREAD

**Issue by Elimi81** [madskristensen/CssTools#4]
### Installed product versions
- Visual Studio: 2017 Professional (v 15.3.5)
- CssTools-extension v 1.0.14

### Description
While having Css Tools installed and enabled Visual Studio crashes while writing css. The crach is not happening when the extension is disabled or not installed. Below is a way to reproduce the issue.

Can you confirm that it is happening to others also?

### Steps to recreate
1. Create new web site project (or any web project) - I used Framework 4.6.2
2. Add css-file to the project
3. Add 
```
body {
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAAUVBMVEX/////88YAAADG8//G8///88bG8//G8//G8//G8//G8///88bG8//G8//G8//G8//G8///88b///8AOIQAAACEOACMYYwAbbW1ZRgAOFJSOAB67migAAAAE3RSTlMAgACMi4KnvI+ekoGmu4d9hYYBr+Q5CwAAAFZJREFUeF7Fi1cOhDAQQ00Set31hHb/g1KkhIEDgD/Gb55kfJ1kzPRTnD0LXXRepgC0iJhf2AUo1YgVUO/VANq2x3FQSb0sq7A3eFjhYO4SP0/7x8vZAFZgBEvzsog7AAAAAElFTkSuQmCC') /*arrow-down.png*/;
}
```
4. Save
5. Try to write new background-image-entry below the first one. IE: **background-image: url('');**
6. Visual Studio will **crach** when you try to write the apostrophe.

From Event Viewer I'm able to see this error and stacktrace:
Log Name:      Application
Source:        .NET Runtime
Date:          12.10.2017 12.53.23
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      (computername)
Description:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.String.ReplaceInternal(System.String, System.String)
   at System.String.Replace(System.String, System.String)
   at CssTools.EmbeddedImageClassifier+<UpdateEmbeddedImageValues>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at CssTools.EmbeddedImageClassifier+<TreeItemsChanged>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by AccessIT** [comment]
Quick question - is that the correct version you listed of the CSS Tools? It seems very old as the current version is 1.1.20 and you have specified 1.0.14

I tried to repo your problem without success but I am using later versions of both Visual Studio and CSS tools.
Visual Studio 2017 15.4.1
CSS Tools 1.1.20
These are public releases so maybe try with them
One thing I did notice is that the closing bracket was added automatically (I think by resharper) as soon as I typed the opening bracket which may change things

![vs image](https://user-images.githubusercontent.com/7320338/31855864-01cc8be6-b6f7-11e7-8f05-854691fd9712.jpg)

In addition to the image above I tried is as a new style in case that is what you meant
![vs image 2](https://user-images.githubusercontent.com/7320338/31855882-9eaafdf8-b6f7-11e7-93be-3fa5a0364b8c.jpg)

**Comment by madskristensen** [comment]
Fixed
